### ISSUE TITLE
How to install desktop environment after installing distros

### ISSUE THREAD

**Issue by shiv123shiv123** [1X1-Tech/Toolloa#3]
I install bionic distro but how to install desktop environment, in your setup tool code it install kali-core why? Pls. provide some suggestions.

**Comment by SaicharanKandukuri** [comment]
To install a desktop environment you can use packages manager of that distro, As you said 
> I install bionic distro

The package manager will be `apt`
You can install XFCE Desktop environment by executing
```bash
#if you are root user
apt install -y xfce4
```
###### I will provide you further instructions on how to start a VNC if you make a new issue or ask here.
And remember as of updates in new android versions in so many syscalls are blocked . Which causing  problems in installing Desktop environments like `kde` But it works in `bionic` [Ubuntu 18.04] Cause it is an older Linux build.


& Kali core is set to install in script cause it contains packages like 
- open ssh
- ftp
- untarnished
- vim
& more 

And it Has good configuration for kali

**Comment by shiv123shiv123** [comment]
Ok thanks, but now i move to tweaked version of kali desktopl, and i have also some issues there because after successful installation process vs-code can not open and when i try to open vnc with other user then it simply closed e.g `#shiee@localhost$ startvnc` then it not start.

**Comment by SaicharanKandukuri** [comment]
Well, I am like a one-man army now for this Repo So Pull requests are welcome. So that we can work together and I can get back to dev work for this.
I actually `desktopl` script is so old and didn't improved it cause I didn't got any response from anyone.
But now I get back to work😊

**Comment by shiv123shiv123** [comment]
I really appreciate your work for this repo, this is amazing because i tried most versions of linux from different sources but this is nicest one and also this support libreoffice without any error runs smoothly. Thanks.

**Comment by SaicharanKandukuri** [comment]
suggested issue : #6
